### ISSUE TITLE
Default to base

### ISSUE THREAD

**Issue by n1mda** [nullic/DPLocalizationManager#6]
If a key is missing in a certain language, how come DPLocalizationManager prints the key instead of defaulting to the Base language?

**Comment by nullic** [comment]
If **DPLocalizationManager** can't find *value* for given *key*, then it return value of **NSLocalizedStringFromTable** macro.

> Base internationalization separates user-facing strings from .storyboard and .xib files.

https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/InternationalizingYourCode/InternationalizingYourCode.html#//apple_ref/doc/uid/10000171i-CH4-SW1
