### ISSUE TITLE
supportedLanguages returns languages not supported

### ISSUE THREAD

**Issue by n1mda** [nullic/DPLocalizationManager#7]
When I run ```[DPLocalizationManager supportedLanguages]``` I get a list of:

```(
    Base,
    ca,
    cs,
    da,
    de,
    el,
    en,
    es,
    fr,
    id,
    it,
    ja,
    ko,
    nb,
    nl,
    nn,
    pl,
    pt,
    "pt_BR",
    ru,
    sv,
    tr,
    uk,
    vi,
    "zh-Hans",
    "zh-Hant"
)```

I do not support these languages in my app. What does supportedLanguages do exactly?

**Comment by n1mda** [comment]
Reason is because I use the Pod ```FormatterKit``` that adds .lproj folders for all these languages. Might want to check that Localizable.strings actually exists in these folders before returning them as a supported language in DPLocalizationManager

**Comment by nullic** [comment]
'supportedLanguages' return all .lproj folders in main bundle (top level).

I may wrong, but if you try to upload such application to appstore, you will get an error. So you must add 'Localizable.strings' file to all the language folders. 

Please, check this https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPInternational/MaintaingYourOwnStringsFiles/MaintaingYourOwnStringsFiles.html
